export const players = ['бека', 'шерхан', 'рафик', 'адиар', 'азамат сагындыков', 'азамат аскаров', 'женя', 'данил', 'маха', 'нурик', 'тимур', 'вова хван', 'вова бондарев'];

export const gameRulesText = "This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text! This is a dummy text!   ";

export const checkInput = (inputName) => {
	for (let i = 0; i < players.length; i++) 
		if (players[i] == inputName.trim().toLowerCase()) 
			return true;
	return false;
};